(()=>{
'use strict';
const $=s=>document.querySelector(s), esc=v=>MWS.esc(v);
let horseTimer=null;
function render(tab){if(tab==='ladder')renderLadder();if(tab==='rps')renderRps();if(tab==='horse')renderHorse();if(tab==='gacha')renderGacha()}
function candidates(){return(MWS.data.contacts||[]).slice().sort((a,b)=>String(a.name||'').localeCompare(String(b.name||''),'ko'))}
function renderLadder(){const el=$('#ladder');if(!el)return;el.innerHTML=`<div class="toolbar"><div><h2>사다리타기</h2><div class="muted">참가자를 줄 단위로 입력하고 결과 항목을 같은 수만큼 입력합니다.</div></div></div><div class="grid cols2"><div class="card field"><label>참가자</label><textarea id="ladderNames" style="width:100%;min-height:220px">A\nB\nC\nD</textarea></div><div class="card field"><label>결과</label><textarea id="ladderResults" style="width:100%;min-height:220px">1\n2\n3\n4</textarea></div></div><div class="card" style="margin-top:10px"><button class="primary" id="ladderRun">사다리 실행</button><div id="ladderOut" style="margin-top:12px"></div></div>`;$('#ladderRun').onclick=()=>{const names=$('#ladderNames').value.split('\n').map(x=>x.trim()).filter(Boolean),res=$('#ladderResults').value.split('\n').map(x=>x.trim()).filter(Boolean);if(names.length<2||names.length!==res.length)return MWS.toast('사다리','참가자와 결과 개수를 동일하게 맞추세요.');const shuffled=[...res];for(let i=shuffled.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[shuffled[i],shuffled[j]]=[shuffled[j],shuffled[i]]}$('#ladderOut').innerHTML=`<div class="ladder-grid" style="--n:${names.length}">${names.map((n,i)=>`<div><div class="ladder-name">${esc(n)}</div><div style="height:160px;border-left:2px solid #54627d;margin-left:50%"></div><div class="ladder-name" style="border-color:#8b5cf6">${esc(shuffled[i])}</div></div>`).join('')}</div>`}}
function renderRps(){const el=$('#rps');if(!el)return;el.innerHTML=`<div class="toolbar"><div><h2>가위바위보</h2><div class="muted">한 번의 클릭으로 무작위 결과를 뽑습니다.</div></div></div><div class="card rps-stage"><div><div id="rpsResult" class="rps-result">?</div><button class="primary" id="rpsRun">뽑기</button></div></div>`;$('#rpsRun').onclick=()=>{const arr=['✊','✌','✋'];$('#rpsResult').textContent=arr[Math.floor(Math.random()*3)]}}
function renderHorse(){clearInterval(horseTimer);const el=$('#horse');if(!el)return;const names=['1번','2번','3번','4번','5번','6번'];el.innerHTML=`<div class="toolbar"><div><h2>경마</h2><div class="muted">각 레인의 속도는 매 프레임 독립적으로 변합니다.</div></div><button class="primary" id="horseRun">START</button></div><div class="card game-board"><div class="horse-track">${names.map((n,i)=>`<div class="horse-lane"><div class="horse-runner" id="runner${i}">${n}</div></div>`).join('')}</div><div id="horseResult" style="margin-top:16px;font-size:20px;font-weight:900"></div></div>`;$('#horseRun').onclick=()=>{const pos=names.map(()=>0);$('#horseResult').textContent='';clearInterval(horseTimer);horseTimer=setInterval(()=>{let win=-1;pos.forEach((p,i)=>{pos[i]+=1+Math.random()*4;const lane=$(`#runner${i}`).parentElement,w=lane.clientWidth-95;$(`#runner${i}`).style.left=Math.min(w,pos[i]/100*w)+'px';if(pos[i]>=100&&win<0)win=i});if(win>=0){clearInterval(horseTimer);$('#horseResult').textContent=`${names[win]} 우승`}},120)}}
function renderGacha(){const el=$('#gacha');if(!el)return;const list=candidates();el.innerHTML=`<div class="toolbar"><div><h2>Gacha 뽑기</h2><div class="muted">현재 연락처에서 중복 없이 무작위로 선택합니다.</div></div><div class="row"><select id="gachaCount"><option>1</option><option>2</option><option selected>3</option><option>5</option><option>8</option></select><button class="primary" id="gachaRun">뽑기</button></div></div><div class="card game-board"><div id="gachaResult" class="gacha-result"></div></div>`;$('#gachaRun').onclick=()=>{const count=Math.min(Number($('#gachaCount').value),list.length),arr=[...list];for(let i=arr.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[arr[i],arr[j]]=[arr[j],arr[i]]}$('#gachaResult').innerHTML=arr.slice(0,count).map(c=>`<div class="gacha-card">${MWS.contactImage(c)?`<img src="${esc(MWS.contactImage(c))}" style="width:110px;height:110px;border-radius:16px;object-fit:cover">`:''}<h3>${esc(c.name)}</h3></div>`).join('')}}
window.MWSGames={render};
})();