const {chromium}=require('playwright');
(async()=>{
  const base='https://mawang-scheduler.majoku.workers.dev';
  const health=await fetch(base+'/api/health').then(r=>r.text());
  if(!health.includes('CF MWS V 1.0.14')) throw new Error('live health version mismatch: '+health.slice(0,300));
  const browser=await chromium.launch({headless:true});
  const page=await browser.newPage({viewport:{width:1440,height:900}});
  const errors=[]; page.on('pageerror',e=>errors.push(String(e)));
  await page.goto(base+'/content-planner.html?v=1.0.14',{waitUntil:'load'}); await page.waitForTimeout(350);
  if((await page.title())!=='MAWANG Content Planner V1.0.14') throw new Error('live planner title mismatch: '+await page.title());
  await page.evaluate(()=>{addTextAtV110(240,200,320,70);clearSelection();window.__dragTrace=[];window.addEventListener('pointerdown',e=>{const r=document.getElementById('board').getBoundingClientRect();window.__dragTrace.push({t:'down',x:e.clientX,y:e.clientY,br:{x:r.x,y:r.y,w:r.width,h:r.height}})},true);window.addEventListener('pointermove',e=>{if(e.buttons){const r=document.getElementById('board').getBoundingClientRect();window.__dragTrace.push({t:'move',x:e.clientX,y:e.clientY,br:{x:r.x,y:r.y,w:r.width,h:r.height}})}},true);window.addEventListener('pointerup',e=>{const r=document.getElementById('board').getBoundingClientRect();window.__dragTrace.push({t:'up',x:e.clientX,y:e.clientY,br:{x:r.x,y:r.y,w:r.width,h:r.height}})},true)});
  const textNode=page.locator('.node.text-node').last(); await textNode.locator('.editable').click(); await page.evaluate(()=>document.activeElement?.blur());
  const stateBefore=await textNode.evaluate(n=>{const e=getEl(n.dataset.id),r=document.getElementById('board').getBoundingClientRect();return{x:e.x,y:e.y,br:{x:r.x,y:r.y,w:r.width,h:r.height}}});
  const hb=await textNode.locator('.drag-handle').boundingBox(); if(!hb)throw new Error('handle missing');
  const sx=hb.x+hb.width/2, sy=hb.y+hb.height/2, ex=sx+100, ey=sy+70;
  await page.mouse.move(sx,sy); await page.mouse.down(); await page.mouse.move(ex,ey,{steps:5}); await page.mouse.up(); await page.waitForTimeout(40);
  const stateAfter=await textNode.evaluate(n=>{const e=getEl(n.dataset.id),r=document.getElementById('board').getBoundingClientRect();return{x:e.x,y:e.y,br:{x:r.x,y:r.y,w:r.width,h:r.height},trace:window.__dragTrace}});
  console.log('DRAG DIAGNOSTIC',JSON.stringify({hb,sx,sy,ex,ey,stateBefore,stateAfter},null,2));
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
