const BUILD='MWS Version 1.0.0';
const SUPABASE_URL='https://nysxcqlewzucbpoaymbg.supabase.co';
const SUPABASE_KEY='sb_publishable_H7VPUOVV6nN7QdaJKO3-lA_-SNrg4mW';
function json(value,status=200,headers={}){return new Response(JSON.stringify(value),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','x-mws-build':BUILD,...headers}})}
function sbHeaders(token=SUPABASE_KEY){return{apikey:SUPABASE_KEY,authorization:`Bearer ${token}`}}
async function verifyAdmin(request){const token=(request.headers.get('authorization')||'').replace(/^Bearer\s+/i,'').trim();if(!token)return null;const u=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:sbHeaders(token)});if(!u.ok)return null;const user=await u.json();if(!user?.id)return null;const p=await fetch(`${SUPABASE_URL}/rest/v1/admin_profiles?user_id=eq.${encodeURIComponent(user.id)}&select=user_id&limit=1`,{headers:sbHeaders(token)});if(!p.ok)return null;const rows=await p.json();return Array.isArray(rows)&&rows.length===1?user:null}
async function ensureSchema(env){await env.DB.prepare(`CREATE TABLE IF NOT EXISTS workspace_parts(scope TEXT NOT NULL,part TEXT NOT NULL,data TEXT NOT NULL,version INTEGER NOT NULL DEFAULT 1,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(scope,part))`).run()}
function publicBase(env){return String(env.MWS_R2_PUBLIC_BASE_URL||'').replace(/\/+$/,'')}
function rewriteMedia(value,base){if(typeof value==='string'){let m=/^\/media\/contact\/([^?]+)(\?.*)?$/.exec(value);if(m)return`${base}/contacts/${m[1]}${m[2]||''}`;m=/^\/media\/workspace\/([^?]+)(\?.*)?$/.exec(value);if(m)return`${base}/workspace/${m[1]}${m[2]||''}`;return value}if(Array.isArray(value))return value.map(v=>rewriteMedia(v,base));if(value&&typeof value==='object'){const o={};for(const[k,v]of Object.entries(value))o[k]=rewriteMedia(v,base);return o}return value}
function parseDataUrl(v){if(typeof v!=='string')return null;const m=/^data:([^;,]+);base64,(.+)$/s.exec(v);if(!m)return null;const type=String(m[1]||'application/octet-stream').toLowerCase();if(!type.startsWith('image/')&&!type.startsWith('video/'))return null;const bin=atob(m[2]),bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);return{type,bytes}}
async function digest(bytes){const h=new Uint8Array(await crypto.subtle.digest('SHA-256',bytes));return[...h].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function externalize(env,value,base){const parsed=parseDataUrl(value);if(parsed){const hash=await digest(parsed.bytes),key=`workspace/mws/${hash}`;await env.IMAGES.put(key,parsed.bytes,{httpMetadata:{contentType:parsed.type},customMetadata:{source:'mws-clean',build:BUILD}});return`${base}/${key}?v=1`}if(Array.isArray(value)){const out=[];for(const v of value)out.push(await externalize(env,v,base));return out}if(value&&typeof value==='object'){const out={};for(const[k,v]of Object.entries(value))out[k]=await externalize(env,v,base);return out}return rewriteMedia(value,base)}
async function hashText(text){const b=new TextEncoder().encode(text),h=new Uint8Array(await crypto.subtle.digest('SHA-256',b));return[...h].slice(0,12).map(x=>x.toString(16).padStart(2,'0')).join('')}
async function bootstrap(env,request){await ensureSchema(env);const base=publicBase(env);if(!base)return json({error:'MWS_R2_PUBLIC_BASE_URL is not configured.'},503);const{results=[]}=await env.DB.prepare('SELECT part,data,version,updated_at FROM workspace_parts WHERE scope=? ORDER BY part').bind('public').all();const sig=results.map(r=>`${r.part}:${r.version}`).join('|'),etag=`"mws-${await hashText(sig)}"`;if(request.headers.get('if-none-match')===etag)return new Response(null,{status:304,headers:{etag,'cache-control':'no-cache','x-mws-build':BUILD}});const parts={};for(const r of results){let v;try{v=JSON.parse(r.data)}catch(_){continue}parts[r.part]={version:Number(r.version)||1,data:rewriteMedia(v,base),updatedAt:r.updated_at}}return json({build:BUILD,backend:'Cloudflare D1 + R2',mediaBaseUrl:base,parts},200,{etag})}
async function save(request,env){const user=await verifyAdmin(request);if(!user)return json({error:'Admin authorization required.'},401);await ensureSchema(env);const base=publicBase(env);if(!base)return json({error:'MWS_R2_PUBLIC_BASE_URL is not configured.'},503);let body;try{body=await request.json()}catch(_){return json({error:'Invalid JSON body.'},400)}if(!body?.parts||typeof body.parts!=='object'||Array.isArray(body.parts))return json({error:'parts object is required.'},400);const normalized={},versions={};for(const[part,raw]of Object.entries(body.parts)){if(!/^[A-Za-z0-9_-]{1,40}$/.test(part))continue;const value=await externalize(env,raw,base),text=JSON.stringify(value);if(new TextEncoder().encode(text).byteLength>10*1024*1024)return json({error:`${part} part is too large.`},413);const row=await env.DB.prepare('SELECT MAX(version) AS v FROM workspace_parts WHERE part=?').bind(part).first(),version=Math.max(1,Number(row?.v)||0)+1;await env.DB.batch(['public','admin'].map(scope=>env.DB.prepare(`INSERT INTO workspace_parts(scope,part,data,version,updated_at) VALUES(?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(scope,part) DO UPDATE SET data=excluded.data,version=excluded.version,updated_at=CURRENT_TIMESTAMP`).bind(scope,part,text,version)));normalized[part]=value;versions[part]=version}return json({ok:true,build:BUILD,normalized,versions})}
export default{async fetch(request,env,ctx){const url=new URL(request.url);try{if(url.pathname==='/api/health')return json({ok:true,build:BUILD,backend:'Cloudflare D1 + R2'});if(url.pathname==='/api/bootstrap'&&request.method==='GET')return await bootstrap(env,request);if(url.pathname==='/api/save'&&request.method==='POST')return await save(request,env);if(url.pathname.startsWith('/api/'))return json({error:'Not found.'},404);return env.ASSETS.fetch(request)}catch(e){console.error(BUILD,e);return json({error:e instanceof Error?e.message:String(e),build:BUILD},500)}}};